### ISSUE TITLE
Cannot fully remove add-in

### ISSUE THREAD

**Issue by emanueldutra** [twighk/tghz-word-tone-annotator#12]
When using the add-in management tool in MS Word to remove the tone annotator add-in there are still some registries that are not removed. It is conflicting with the standalone Software Key that I'm trying to install. I looked for residual files that could be interfering, but wasn't able to find them. Any recommendations?
Thanks!

**Comment by twighk** [comment]
Usually, i uninstall it with add/remove programs in control panel. Please let me know if that works.

As far as I'm aware there's only one extra file it makes (from memory, it's a hidden file in your documents folder to store the dictionary corrections), but the Microsoft's installer and the add-in framework might add more.
